[package]
authors = ["Darren Barklie <darren@craftapplied.com>"]
edition = "2018"
name = "egghead-rust-cli-digital-garden"
version = "0.1.0"

[[bin]]
name = "garden"
path = "src/main.rs"

[dependencies]
color-eyre = "0.6.1"
structopt = "0.3.26"
